# Generated by Django 2.1.2 on 2018-11-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64,serialize=True)),
                ('address', models.CharField(max_length=128)),
                ('pinCode', models.IntegerField()),
                ('Phone_no', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('UID', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('Driving_License', models.CharField(max_length=32)),
                ('Driving_License_image', models.FileField(upload_to='photos/collector/DL')),
                ('image', models.FileField(upload_to='photos/collector')),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64,serialize=True)),
                ('address', models.CharField(max_length=128)),
                ('pinCode', models.IntegerField()),
                ('Phone_no', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('UID', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('image', models.FileField(upload_to='photos/doner')),
            ],
        ),
    ]
