# Generated by Django 2.1.2 on 2018-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('proprietor', models.CharField(max_length=64)),
                ('license_no', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pincode', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('Phone_no', models.IntegerField()),
                ('image', models.FileField(upload_to='photos/acceptor')),
            ],
        ),
    ]
