# Generated by Django 2.1.2 on 2018-11-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0003_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_assigned_time', models.DateTimeField(auto_now=True)),
                ('vehicle_return_time', models.DateTimeField(auto_now=True)),
                ('distance', models.FloatField()),
                ('collector_id', models.ManyToManyField(blank=True, to='MedicalDonation.Collector')),
                ('destination', models.ManyToManyField(blank=True, to='MedicalDonation.Doner')),
                ('vehicle_id', models.ManyToManyField(blank=True, to='MedicalDonation.vehicle')),
            ],
        ),
    ]
