# Generated by Django 2.1.2 on 2018-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0008_auto_20181110_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_vehicle',
            name='collector_id',
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='collector_id',
            field=models.ManyToManyField(blank=True, related_name='_assigned_vehicle_collector_id_+', to='MedicalDonation.Collector'),
        ),
        migrations.RemoveField(
            model_name='assigned_vehicle',
            name='destination',
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='destination',
            field=models.ManyToManyField(blank=True, related_name='_assigned_vehicle_destination_+', to='MedicalDonation.Doner'),
        ),
        migrations.RemoveField(
            model_name='assigned_vehicle',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='vehicle_id',
            field=models.ManyToManyField(blank=True, related_name='_assigned_vehicle_vehicle_id_+', to='MedicalDonation.vehicle'),
        ),
    ]
