# Generated by Django 2.1.2 on 2018-11-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0009_auto_20181110_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_vehicle',
            name='collector_id',
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='collector_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Collector'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='assigned_vehicle',
            name='destination',
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='destination',
            field=models.ForeignKey(blank=True, default='#17 kodipalya road near family mart kengeri1st floorBangalore', on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Doner', to_field='address'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='assigned_vehicle',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.vehicle'),
            preserve_default=False,
        ),
    ]
