# Generated by Django 2.1.2 on 2018-11-10 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0010_auto_20181110_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_legger',
            name='acceptor_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Acceptor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_legger',
            name='collector_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Collector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_legger',
            name='donor_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Doner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_legger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 22, 50, 214103)),
        ),
        migrations.AddField(
            model_name='medicine_legger',
            name='medicine_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine_legger',
            name='medicine_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_legger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 22, 50, 214103)),
        ),
    ]
