# Generated by Django 2.1.2 on 2018-11-10 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0012_auto_20181110_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('acceptor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Acceptor')),
                ('collector_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Collector')),
                ('donor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.Doner')),
                ('medicine_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.medicine')),
                ('vehicle_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalDonation.vehicle')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 36, 24, 706079)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 36, 24, 706079)),
        ),
    ]
