# Generated by Django 2.1.2 on 2018-11-10 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0013_auto_20181110_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 37, 39, 710791)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 37, 39, 710791)),
        ),
    ]
