# Generated by Django 2.1.2 on 2018-11-16 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0014_auto_20181110_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptor',
            name='UID',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 16, 1, 34, 954611)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 16, 1, 34, 953614)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 16, 1, 34, 953614)),
        ),
    ]
