# Generated by Django 2.1.2 on 2018-11-17 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0015_auto_20181116_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 14, 35, 36, 892589)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 14, 35, 36, 890594)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 14, 35, 36, 890594)),
        ),
    ]
