# Generated by Django 2.1.2 on 2018-11-19 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0016_auto_20181117_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='password',
        ),
        migrations.AlterField(
            model_name='acceptor',
            name='image',
            field=models.FileField(upload_to='acceptor'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='image',
            field=models.FileField(upload_to='collector/image'),
        ),
        migrations.AlterField(
            model_name='doner',
            name='image',
            field=models.FileField(upload_to='doner'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 0, 4, 21, 168360)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 0, 4, 21, 167363)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 0, 4, 21, 167363)),
        ),
    ]
