# Generated by Django 2.1.2 on 2018-11-19 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalDonation', '0017_auto_20181120_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptor',
            name='image',
            field=models.ImageField(upload_to='acceptor'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='Driving_License_image',
            field=models.ImageField(upload_to='photos/collector/DL'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='image',
            field=models.ImageField(upload_to='collector/image'),
        ),
        migrations.AlterField(
            model_name='doner',
            name='image',
            field=models.ImageField(upload_to='doner'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 1, 17, 59, 399817)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='indate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 1, 17, 59, 399817)),
        ),
        migrations.AlterField(
            model_name='medicine_ledger',
            name='outdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 1, 17, 59, 399817)),
        ),
    ]
